BPM_VERSION=1

BPM_DEPENDENCIES=(
  git 
  curl
  zip
  realpath
)

# Directories
BPM_DIR_PATH="$HOME/.local/.bpm"
BPM_BIN_DIR_PATH="$BPM_DIR_PATH/bin"
BPM_STATE_DIR_PATH="$BPM_DIR_PATH/state"
BPM_REPOS_DIR_PATH="$BPM_STATE_DIR_PATH/repos"
BPM_DEPS_DIR_PATH="$BPM_DIR_PATH/deps"
BPM_TMP_DIR_PATH="$BPM_DIR_PATH/tmp"
BPM_CACHE_DIR_PATH="$BPM_DIR_PATH/cache"
BPM_SRC_DIR_PATH="$BPM_DIR_PATH/src"
BPM_EXPORT_DIR_PATH="$BPM_BIN_DIR_PATH/export"

BPM_MKD=(
  "$BPM_BIN_DIR_PATH"
  "$BPM_DIR_PATH"
  "$BPM_DEPS_DIR_PATH"
  "$BPM_STATE_DIR_PATH"
  "$BPM_REPOS_DIR_PATH"
  "$BPM_TMP_DIR_PATH"
  "$BPM_CACHE_DIR_PATH"
  "$BPM_SRC_DIR_PATH"
  "$BPM_EXPORT_DIR_PATH"
)

# Scripts/Files
BPM_CORE_PATH="$BPM_SRC_DIR_PATH/core.sh"
BPM_RUNNER_PATH="$BPM_SRC_DIR_PATH/runner.sh"
BPM_BASH_INSERTION_PATH="$BPM_SRC_DIR_PATH/insert.sh"
BPM_AUTOCOMPLETE_PATH="$BPM_SRC_DIR_PATH/cmp.sh"
BPM_LOCATOR_PATH="$BPM_STATE_DIR_PATH/locator.sh"
BPM_REPOS_SH_PATH="$BPM_STATE_DIR_PATH/repos.sh"
BPM_INSTALL_LOCK_PATH="$BPM_TMP_DIR_PATH/bpm-install.lock"
BPM_LOGS_PATH="$BPM_CACHE_DIR_PATH/logs"
BPM_EXPORTER_PATH="$BPM_SRC_DIR_PATH/exporter.sh"
BPM_EXPORTED_PACKAGES_PATH="$BPM_STATE_DIR_PATH/exported-packages.sh"
