BPM_VERSION=1

BPM_DEPENDENCIES=(
  git 
  curl
)

# Directories
BPM_BIN_DIR_PATH="$HOME/.local/bin"
BPM_DIR_PATH="$HOME/.local/.bpm"
BPM_STATE_DIR_PATH="$BPM_DIR_PATH/state"
BPM_REPOS_DIR_PATH="$BPM_STATE_DIR_PATH/repos"
BPM_DEPS_DIR_PATH="$BPM_DIR_PATH/deps"
BPM_TMP_DIR_PATH="$BPM_DIR_PATH/tmp"

BPM_MKD=(
  "$BPM_BIN_DIR_PATH"
  "$BPM_DIR_PATH"
  "$BPM_DEPS_DIR_PATH"
  "$BPM_STATE_DIR_PATH"
  "$BPM_REPOS_DIR_PATH"
  "$BPM_TMP_DIR_PATH"
)

# Scripts
BPM_LOCATOR_PATH="$BPM_STATE_DIR_PATH/locator.sh"
BPM_CORE_PATH="$BPM_DIR_PATH/core.sh"
BPM_RUNNER_PATH="$BPM_DIR_PATH/runner.sh"
BPM_REPOS_SH_PATH="$BPM_STATE_DIR_PATH/repos.sh"
BPM_INSTALL_LOCK_PATH="$TMPDIR/bpm-install.lock"
